 [[redirects]]
   from = "/login"
   to = "https://modulz-abdul.firebaseapp.com/"
   status = 200
# [[redirects]]
#   from = "/account/*"
#   to = "https://modulz-test.firebaseapp.com/account/:splat"
#   status = 200
#   force = true
  
