# [[redirects]]
#   from = "/projects/*"
#   to = "https://modulz-test.firebaseapp.com/:splat"
#   status = 200
#   force = true

/login  https://modulz-abdul.firebaseapp.com/login  200

# [[redirects]]
#   from = "/account/*"
#   to = "https://modulz-test.firebaseapp.com/account/:splat"
#   status = 200
#   force = true
  
