# [[redirects]]
#   from = "/projects/*"
#   to = "https://modulz-test.firebaseapp.com/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/login/*"
#   to = "https://modulz-test.firebaseapp.com/login/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/account/*"
#   to = "https://modulz-test.firebaseapp.com/account/:splat"
#   status = 200
#   force = true
  
