import React from 'react';
import {
  Flexbox,
  Box,
  List,
  Heading,
  Text,
  Button,
  Select
} from 'radix-ds';

function ComposerProperties() {
  return (
    <Box
      p3
      bl
      bcgray300
      fs0
      style={{
        width: '20%',
        borderColor: 'hsl(208, 18%, 22%)',
        overflow: 'hidden',
      }}
    >
      <Heading
        size1
        mb2
      >
        Layout
      </Heading>
      <Box
        table
        w100
      >
        <Box
          tablerow
        >
          <Box
            tablecell
            alignmiddle
            pr2
          >
            <Text
              size1
              gray600
            >
              Direction
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Flexbox>
              <Button
                size1
                left
              >
                Row
              </Button>
              <Button
                size1
                right
              >
                Column
              </Button>
            </Flexbox>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Align
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Stretch
              </option>
              <option>
                Baseline
              </option>
            </Select>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Distribute
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Space between
              </option>
              <option>
                Space around
              </option>
            </Select>
          </Box>
        </Box>
      </Box>
      <Heading
        size1
        mb2
      >
        Layout
      </Heading>
      <Box
        table
        w100
      >
        <Box
          tablerow
        >
          <Box
            tablecell
            alignmiddle
            pr2
          >
            <Text
              size1
              gray600
            >
              Direction
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Flexbox>
              <Button
                size1
                left
              >
                Row
              </Button>
              <Button
                size1
                right
              >
                Column
              </Button>
            </Flexbox>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Align
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Stretch
              </option>
              <option>
                Baseline
              </option>
            </Select>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Distribute
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Space between
              </option>
              <option>
                Space around
              </option>
            </Select>
          </Box>
        </Box>
      </Box>
      <Heading
        size1
        mb2
      >
        Layout
      </Heading>
      <Box
        table
        w100
      >
        <Box
          tablerow
        >
          <Box
            tablecell
            alignmiddle
            pr2
          >
            <Text
              size1
              gray600
            >
              Direction
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Flexbox>
              <Button
                size1
                left
              >
                Row
              </Button>
              <Button
                size1
                right
              >
                Column
              </Button>
            </Flexbox>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Align
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Stretch
              </option>
              <option>
                Baseline
              </option>
            </Select>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Distribute
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Space between
              </option>
              <option>
                Space around
              </option>
            </Select>
          </Box>
        </Box>
      </Box>
      <Heading
        size1
        mb2
      >
        Layout
      </Heading>
      <Box
        table
        w100
      >
        <Box
          tablerow
        >
          <Box
            tablecell
            alignmiddle
            pr2
          >
            <Text
              size1
              gray600
            >
              Direction
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Flexbox>
              <Button
                size1
                left
              >
                Row
              </Button>
              <Button
                size1
                right
              >
                Column
              </Button>
            </Flexbox>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Align
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Stretch
              </option>
              <option>
                Baseline
              </option>
            </Select>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Distribute
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Space between
              </option>
              <option>
                Space around
              </option>
            </Select>
          </Box>
        </Box>
      </Box>
      <Heading
        size1
        mb2
      >
        Layout
      </Heading>
      <Box
        table
        w100
      >
        <Box
          tablerow
        >
          <Box
            tablecell
            alignmiddle
            pr2
          >
            <Text
              size1
              gray600
            >
              Direction
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Flexbox>
              <Button
                size1
                left
              >
                Row
              </Button>
              <Button
                size1
                right
              >
                Column
              </Button>
            </Flexbox>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Align
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Stretch
              </option>
              <option>
                Baseline
              </option>
            </Select>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Distribute
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Space between
              </option>
              <option>
                Space around
              </option>
            </Select>
          </Box>
        </Box>
      </Box>
      <Heading
        size1
        mb2
      >
        Layout
      </Heading>
      <Box
        table
        w100
      >
        <Box
          tablerow
        >
          <Box
            tablecell
            alignmiddle
            pr2
          >
            <Text
              size1
              gray600
            >
              Direction
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Flexbox>
              <Button
                size1
                left
              >
                Row
              </Button>
              <Button
                size1
                right
              >
                Column
              </Button>
            </Flexbox>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Align
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Stretch
              </option>
              <option>
                Baseline
              </option>
            </Select>
          </Box>
        </Box>
        <Box
          pt2>
        </Box>
        <Box
          tablerow
        >
          <Box
            tablecell
            pr2
            alignmiddle
          >
            <Text
              size1
              gray600
            >
              Distribute
            </Text>
          </Box>
          <Box
            tablecell
            alignmiddle
          >
            <Select>
              <option>
                Start
              </option>
              <option>
                Center
              </option>
              <option>
                End
              </option>
              <option>
                Space between
              </option>
              <option>
                Space around
              </option>
            </Select>
          </Box>
        </Box>
      </Box>
    </Box>
  );
}

export default ComposerProperties;
